# -*- coding: utf-8 -*-
"""Untitled0.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1osA1ReNd3WBEX_KkggYQ8ZDB_Tmktqwq

1. ByteSize & TimeDuration Parser Classes
"""

# @title Default title text
import re

class ByteSize:
    UNITS = {
        'B': 1,
        'KB': 1024,
        'MB': 1024**2,
        'GB': 1024**3,
        'TB': 1024**4,
        'PB': 1024**5
    }

    def __init__(self, value: str):
        self.original = value
        self.bytes = self._parse(value)

    def _parse(self, value: str) -> int:
        match = re.fullmatch(r"(\d+(?:\.\d+)?)(B|KB|MB|GB|TB|PB)", value.strip().upper())
        if not match:
            raise ValueError(f"Invalid ByteSize: {value}")
        number, unit = match.groups()
        return int(float(number) * self.UNITS[unit])

    def get_bytes(self):
        return self.bytes

class TimeDuration:
    UNITS = {
        'ms': 1,
        's': 1000,
        'm': 60_000,
        'h': 3_600_000
    }

    def __init__(self, value: str):
        self.original = value
        self.milliseconds = self._parse(value)

    def _parse(self, value: str) -> int:
        match = re.fullmatch(r"(\d+(?:\.\d+)?)(ms|s|m|h)", value.strip().lower())
        if not match:
            raise ValueError(f"Invalid TimeDuration: {value}")
        number, unit = match.groups()
        return int(float(number) * self.UNITS[unit])

    def get_milliseconds(self):
        return self.milliseconds

""" 2. AggregateStats Simulation in Python"""

class AggregateStats:
    def __init__(self, size_column, time_column, output_size_col, output_time_col):
        self.size_column = size_column
        self.time_column = time_column
        self.output_size_col = output_size_col
        self.output_time_col = output_time_col
        self.total_bytes = 0
        self.total_millis = 0
        self.count = 0

    def accumulate(self, row):
        size = ByteSize(row[self.size_column])
        time = TimeDuration(row[self.time_column])
        self.total_bytes += size.get_bytes()
        self.total_millis += time.get_milliseconds()
        self.count += 1

    def finalize(self):
        return {
            self.output_size_col: round(self.total_bytes / (1024 * 1024), 3),  # MB
            self.output_time_col: round(self.total_millis / 1000, 3)  # Seconds
        }

"""3. Unit Tests"""

def test_byte_size():
    assert ByteSize("10MB").get_bytes() == 10 * 1024 * 1024
    assert ByteSize("1.5GB").get_bytes() == int(1.5 * 1024**3)
    print("ByteSize tests passed.")

def test_time_duration():
    assert TimeDuration("2s").get_milliseconds() == 2000
    assert TimeDuration("1.5h").get_milliseconds() == int(1.5 * 3600000)
    print("TimeDuration tests passed.")

def test_aggregation():
    rows = [
        {"data_transfer_size": "10MB", "response_time": "2s"},
        {"data_transfer_size": "5MB", "response_time": "1s"},
    ]
    directive = AggregateStats("data_transfer_size", "response_time", "total_size_mb", "total_time_sec")
    for row in rows:
        directive.accumulate(row)
    result = directive.finalize()
    assert result["total_size_mb"] == 15.0
    assert result["total_time_sec"] == 3.0
    print("Aggregation test passed.")

"""4. Run Everything"""

if __name__ == "__main__":
    test_byte_size()
    test_time_duration()
    test_aggregation()

[
    {"data_transfer_size": "10MB", "response_time": "2s"},
    {"data_transfer_size": "5MB", "response_time": "1s"},
    {"data_transfer_size": "500KB", "response_time": "500ms"},
]

